services:
  backend:
    image: ghcr.io/uktveris/speaksers-backend:latest
    command: sh -c "npm run seed:prod && npm run start"
    network_mode: host
    env_file: ".env"
    init: true
    restart: unless-stopped
