services:
  backend:
    image: ghcr.io/uktveris/speaksers-backend:latest
    command: sh -c "npm run seed:preview && npm run preview"
    network_mode: host
    env_file: ".env.preview"
    init: true
    restart: unless-stopped
