services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run seed:dev && npm run dev"
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
    env_file: ".env.development"
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
